version: "3.8"
services:
  db:
    image: mysql
    hostname: db
    volumes:
      - ./src/main/resources/db/migration/:/docker-entrypoint-initdb.d
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=tlc
      - MYSQL_PASSWORD=tlc
  etherpad:
    image: etherpad/etherpad:latest
    hostname: etherpad
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    hostname: mail
    restart: always
    ports:
      - "2525:25"
  backend:
    container_name: backend
    image: apitest
    ports:
      - 8080:8080
    environment:
      - doodle.internalPadUrl=http://etherpad:9001/
      - doodle.externalPadUrl=http://etherpad:9001/
      - quarkus.datasource.jdbc.url=jdbc:mysql://db:3306/tlc?useUnicode=true&serverTimezone=Europe/Paris
    restart: always
  frontend:
    container_name: frontend
    image: fronttest
    ports:
      - 90:80
    volumes:
      - ./server_conf/api.conf:/etc/nginx/conf.d/api.conf
      - ./server_conf/pad.conf:/etc/nginx/conf.d/pad.conf
      - ./server_conf/myadmin.conf:/etc/nginx/conf.d/myadmin.conf
  myadmin:
    image: phpmyadmin
    container_name: myadmin
    environment:
      - PMA_HOST=db
    restart: always

